export const DIALOG_ACTIVE_SET = 'DIALOG_ACTIVE_SET'

export const CONNECTION_STATUS_ACTIVATE = 'CONNECTION_STATUS_ACTIVATE'
export const CONNECTION_STATUS_DEACTIVATE = 'CONNECTION_STATUS_DEACTIVATE'

export const ROOM_CREATE = 'ROOM_CREATE'
export const ROOM_CREATE_BATCH = 'ROOM_CREATE_BATCH'
export const ROOM_UPDATE = 'ROOM_UPDATE'
export const ROOM_DELETE = 'ROOM_DELETE'
export const ROOM_SELECT = 'ROOM_SELECT'
export const ROOM_RESET = 'ROOM_RESET'

export const ROOM_ONLINE_CREATE = 'ROOM_ONLINE_CREATE'
export const ROOM_ONLINE_CREATE_BATCH = 'ROOM_ONLINE_CREATE_BATCH'
export const ROOM_ONLINE_DELETE = 'ROOM_ONLINE_DELETE'

export const ROOM_IS_TYPING = 'ROOM_IS_TYPING'
export const ROOM_STOPPED_TYPING = 'ROOM_STOPPED_TYPING'

export const PROFILE_CREATE = 'PROFILE_CREATE'
export const PROFILE_UPDATE = 'PROFILE_UPDATE'

export const PROFILE_CURRENT_USER_CREATE = 'PROFILE_CURRENT_USER_CREATE'

export const MESSAGE_CREATE = 'MESSAGE_CREATE'
export const MESSAGE_UPDATE = 'MESSAGE_UPDATE'
export const MESSAGE_DELETE = 'MESSAGE_DELETE'
export const MESSAGE_SENT_CREATE = 'MESSAGE_SENT_CREATE'
